export const GET_TEXTAREA = "GET_TEXTAREA";
export const SEND_TO_REDUX = "SEND_TO_REDUX";
export const SEND_PRODSELECTION_TO_REDUX = "SEND_PRODSELECTION_TO_REDUX";


const PRODUCT_SOW = {
  DXI_PRODUCTS: 'DXI_PRODUCTS',
  ENCRYPTION_KEY_MANAGER_PRODUCTS: 'ENCRYPTION_KEY_MANAGER_PRODUCTS',
  QUANTUM_LATTUS_STORAGE: 'QUANTUM_LATTUS_STORAGE',
  QUANTUM_SCALARI_3LTO: 'QUANTUM_SCALARI_3LTO'
};

export { PRODUCT_SOW }